# Generated by Django 6.0.5 on 2026-05-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('unit', models.CharField(max_length=32)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(max_length=240)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(default='US', max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('meter_aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=240)),
                ('uploaded_by', models.CharField(default='Demo Analyst', max_length=160)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('normalized_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('suspicious_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('schema_version', models.CharField(default='prototype-v1', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('ingestion_mode', models.CharField(max_length=80)),
                ('owner', models.CharField(blank=True, max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('parse_status', models.CharField(choices=[('normalized', 'Normalized'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], max_length=16)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingest.ingestionbatch')),
            ],
            options={
                'ordering': ['batch_id', 'row_number'],
                'unique_together': {('batch', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingest.sourcesystem'),
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_key', models.CharField(db_index=True, max_length=180)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=16)),
                ('category', models.CharField(max_length=80)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=40)),
                ('meter_id', models.CharField(blank=True, max_length=80)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=32)),
                ('canonical_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('canonical_unit', models.CharField(blank=True, max_length=32)),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for audit')], default='needs_review', max_length=16)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('analyst_notes', models.TextField(blank=True)),
                ('edited_from_source', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingest.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingest.facility')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingest.ingestionbatch')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_record', to='ingest.rawrecord')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingest.sourcesystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingest.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_systems', to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='ingest.tenant'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='System', max_length=160)),
                ('action', models.CharField(max_length=80)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.activityrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sourcesystem',
            unique_together={('tenant', 'source_type', 'name')},
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_codes', to='ingest.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_lookups', to='ingest.tenant')),
            ],
            options={
                'ordering': ['plant_code'],
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('tenant', 'key', 'unit')},
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingest_acti_tenant__16ec04_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingest_acti_tenant__a53150_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'category'], name='ingest_acti_tenant__aef9f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityrecord',
            unique_together={('tenant', 'source_system', 'source_record_key', 'raw_fingerprint')},
        ),
    ]
